Add PR description template
3778/.github pull request #1
Opened 2020-05-27 19:48 UTC by lucastt

That's a draft version of a PR description template. Please let me know your opinions and suggestions.

2020-05-27 20:38 UTC, m4rcelofs commented on PULL_REQUEST_TEMPLATE.md
> +Many of these questions are optional, but please have in mind that a better description lead to a better review.
```suggestion
Many of these questions are optional, but please keep in mind that a better description leads to a better review.
```

2020-05-27 20:38 UTC, m4rcelofs commented on PULL_REQUEST_TEMPLATE.md
> +If you need the help of any person or team to apply these changes, please address to them in the end of the description or mark them as reviwers, if it makes more sense.
```suggestion
If you need the help of any person or team to apply these changes, please `@` them in the end of the description or mark them as reviewers, if it makes more sense.
```

2020-05-27 20:38 UTC, m4rcelofs commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] The commit message follows our guidelines;
maybe link to guidelines?

2020-05-27 20:38 UTC, m4rcelofs commented on PULL_REQUEST_TEMPLATE.md
> +* There is anyone more suited to test the changes introduced by this pull request?
```suggestion
* Is anyone more suited to test the changes introduced by this pull request?
```

2020-05-27 20:51 UTC, lucastt commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] The commit message follows our guidelines;
It would be better, but we don't have a guideline yet. It is one of the objectives of the git policy we are building. I wrote it here as a provocation or reminder, do you think is better to keep it off the template until we have proper guidelines?

2020-05-27 23:36 UTC, OctavioBR reviewed
I thought we agreed pointing out some key questions to help describing the PR **context** and **overview**.
This feels more like a "check-list" to me, which I don't believe to be relevant on every change... I know, we ca "N/A", but I would rather remove the questions instead of cluttering up the PR description. IDK, maybe the "What's the purpose of this pull request?" is the king question, always relevant (and implicit to me).

I've tried a little exercise picking some of my old short PRs and asking the 8 questions:
1. [PoC: Alpine Linux container with glibc support](https://github.com/3778/docker-galpine/pull/1)
2. [Fix incorrect physician wallet & location automatic filter](https://github.com/3778/daher/pull/1350)
3. [Fix missing user IDs in our tracking data](https://github.com/3778/daher/pull/1369)
4. [Avoid sending filter without value for enum, number and string types](https://github.com/3778/daher/pull/1332)
5. [Add lit-datepicker with paper-input web-components](https://github.com/3778/daher/pull/1197)
6. [Reactivate Agenda menu](https://github.com/3778/daher/pull/1325)

Some have messy commit messages, others don't add tests and documentation. But I think the most important thing is describing _what_ it's trying to accomplish and _why_. Avoiding much as possible **huge** PRs, and answering those two, are the most succinct way of easing code review, I believe...

:rainbow: _Formatting TOC opinion:_
If so many sections should be described, I prefer using **headings** (3rd or 4th level) instead of **bullets** to better organize the description.

2020-05-28 14:54 UTC, lucastt commented
> I thought we agreed pointing out some key questions to help describing the PR **context** and **overview**.
> This feels more like a "check-list" to me, which I don't believe to be relevant on every change... I know, we ca "N/A", but I would rather remove the questions instead of cluttering up the PR description. IDK, maybe the "What's the purpose of this pull request?" is the king question, always relevant (and implicit to me).
> 
> I've tried a little exercise picking some of my old short PRs and asking the 8 questions:
> 
>     1. [PoC: Alpine Linux container with glibc support](https://github.com/3778/docker-galpine/pull/1)
> 
>     2. [Fix incorrect physician wallet & location automatic filter](https://github.com/3778/daher/pull/1350)
> 
>     3. [Fix missing user IDs in our tracking data](https://github.com/3778/daher/pull/1369)
> 
>     4. [Avoid sending filter without value for enum, number and string types](https://github.com/3778/daher/pull/1332)
> 
>     5. [Add lit-datepicker with paper-input web-components](https://github.com/3778/daher/pull/1197)
> 
>     6. [Reactivate Agenda menu](https://github.com/3778/daher/pull/1325)
> 
> 
> Some have messy commit messages, others don't add tests and documentation. But I think the most important thing is describing _what_ it's trying to accomplish and _why_. Avoiding much as possible **huge** PRs, and answering those two, are the most succinct way of easing code review, I believe...

I got your point.

1. The check list is for the developer submitting the pull request, it lists some actions that should be default. Some times you don't need to add documentation, but really often you should add tests and, definitely, you should avoid messy commit messages. It is a reminder, and in any case, if the check does not apply for your PR you just don't check it, in any way it will not slow you down or make the PR description worst, in the worst case the reviewer will ignore it, in the best one the reviewer will ask if it really wasn't necessary.

2. There is a lot of questions, I agree with you, but I think all of then bring a piece of information that can be useful, of coarse in short PRs some of these questions will not apply, but the template is made to be generic. But I agree with you in the point that it brings some bureaucracy to our PRs, but I think it deserves a test, to see if this template is slowing us down or making people procrastinate on the PR opening.

3. Overall I think these questions bring a lot of useful information, some of this information we could get reading and understanding the PR, but if you start your review knowing all of it is so much easier to review the changes, which in my opinion is a task with a heavier toll on the team since several people will stop what they are doing to review what you've done.

4. If we see that for some teams this PR template applies better and for other teams it does not apply at all, we can make a customized PR template for the exceptions and do not use the generic one.

> rainbow _Formatting TOC opinion:_
> If so many sections should be described, I prefer using **headings** (3rd or 4th level) instead of **bullets** to better organize the description.

Yeah, I had a lot of doubts in the formatting, I'll make the changes and see how it looks.

2020-08-31 19:13 UTC, m4rcelofs approved these changes

2020-08-31 19:13 UTC, m4rcelofs commented on PULL_REQUEST_TEMPLATE.md
> +If you need the help of any person or team to apply these changes, please `@` them in the end of the description or mark them as reviewers, if it makes more sense.
```suggestion
<!---
Thank you for contributing, please fill these checks and give more information about the changes you're introducing.
Many of these questions are optional, but please keep in mind that a better description leads to a better review.
For questions that don't apply to your changes, just answer `N/A`.

If you need the help of any person or team to apply these changes, please `@` them in the end of the description or mark them as reviewers, if it makes more sense.
--->
```
Using it as a comment shows it to the person opening the PR but hides it from everyone else when rendering.

2020-08-31 19:16 UTC, m4rcelofs requested changes
Can we merge this after the fixes? Tracking which repos have this file or not is becoming a big pain

2020-08-31 19:16 UTC, m4rcelofs commented on PULL_REQUEST_TEMPLATE.md
> +If you need the help of any person or team to apply these changes, please `@` them in the end of the description or mark them as reviewers, if it makes more sense.
```suggestion
<!---
Thank you for contributing, please fill these checks and give more information about the changes you're introducing.
Many of these questions are optional, but please keep in mind that a better description leads to a better review.
For questions that don't apply to your changes, just answer `N/A`.

If you need the help of any person or team to apply these changes, please `@` them in the end of the description or mark them as reviewers, if it makes more sense.
--->
```

Using it as a comment shows it to the person opening the PR but hides it from everyone else when rendering.

2020-08-31 19:16 UTC, m4rcelofs commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] The commit message follows our [guidelines](https://3778.atlassian.net/wiki/spaces/ENG/pages/206897153/Git+GitHub#Commit-Message);
```suggestion
- [ ] The commit message follows our [guidelines](https://3778.atlassian.net/wiki/spaces/ENG/pages/252543089/How+We+Use+GitHub);
```

Added a link to the new related page

2020-08-31 22:29 UTC, OctavioBR approved these changes

2020-09-01 12:07 UTC, thiagocaiubi reviewed
After reviewing the docs I'm bit concerned it might not work for private repositories. 😒 

https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

> You can create default community health files, such as CONTRIBUTING and CODE_OF_CONDUCT. Default files will be used for any public repository owned by the account that does not contain its own file of that type.

2020-09-01 12:07 UTC, thiagocaiubi commented
> Can we merge this after the fixes? Tracking which repos have this file or not is becoming a big pain

Agree. 👍

2020-09-01 14:10 UTC, thiagocaiubi commented
Sorry, didn't mean to close. 😞

2020-09-01 15:02 UTC, m4rcelofs commented
> After reviewing the docs I'm bit concerned it might not work for private repositories. unamused
> 
> https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file
> 
> > You can create default community health files, such as CONTRIBUTING and CODE_OF_CONDUCT. Default files will be used for any public repository owned by the account that does not contain its own file of that type.

[This](https://github.community/t/issue-template-for-organization-does-not-work/2049/9) suggests using .github (repo) / .github (folder) / PULL_REQUEST_TEMPLATE.md

2020-09-01 15:48 UTC, thiagocaiubi commented
> > After reviewing the docs I'm bit concerned it might not work for private repositories. unamused
> > https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file
> > > You can create default community health files, such as CONTRIBUTING and CODE_OF_CONDUCT. Default files will be used for any public repository owned by the account that does not contain its own file of that type.
> 
> [This](https://github.community/t/issue-template-for-organization-does-not-work/2049/9) suggests using .github (repo) / .github (folder) / PULL_REQUEST_TEMPLATE.md

Done.

2020-09-01 15:48 UTC, m4rcelofs approved these changes

2020-09-02 12:37 UTC, dvolpato reviewed
:clap: :clap: :clap:

2020-09-15 14:24 UTC, thiagocaiubi approved these changes

2020-09-15 14:26 UTC, merged